### ISSUE TITLE
[debarcoder] subscript out of bounds

### ISSUE THREAD

**Issue by esimonds** [ParkerICI/premessa#1]
Thanks for sharing premessa with the world! I tried it on a 350MB file from Rachel's normalizer and it worked fine. I then tried it on a 3.07GB file from the Fluidigm CyTOF2 normalizer and got a "subscript out of bounds" error. I'll send you a link via email to download the 3.07GB file if you'd like to test it yourself. 

Erin

**Comment by pfgherardini** [comment]
This was due to the barcoding channels being missing in the file. I will eventually add a more helpful error message, but I am closing this for now
