### ISSUE TITLE
Package is not available for R 3.4.4 or higher

### ISSUE THREAD

**Issue by ollllllllllo** [ParkerICI/premessa#15]
Package ‘ParkerICI/premessa’ is not available (for R version 3.4.4)

**Comment by SamGG** [comment]
I don't believe it. Please do write the code you wrote in order to install premessa. Without this code, it's difficult to understand this error. Did you really follow the installation process? What is your OS?
Best.

**Comment by pfgherardini** [comment]
Hi,

From the error message you mentioned it seems like you are trying to install premessa using the R `install.packages` R function. This will not work as this package is not on CRAN. You need to use the `install_github` function from the `devtools` package to install premessa.

Please make sure to review the installation instructions in the README and let me know if you encounter problems.

Thanks

**Comment by ollllllllllo** [comment]
Thanks for your help, Problem solved. I was able to install the package but couldn't use it, only pops out a blank window. I removed the library and re-installed R,  devtools + premessa, suddenly everything works. Maybe some packages I previously installed cause the problem with premessa. 
Anyway, the package works just fine.

**Comment by pfgherardini** [comment]
Perfect, glad to know everything is solved
