### ISSUE TITLE
Normalizer dot plots for gating are overlapping on OS X (using Rstudio)

### ISSUE THREAD

**Issue by esimonds** [ParkerICI/premessa#17]
- My configuration:
  - OS X Sierra or High Sierra (tried both)
  - Premessa version 0.1.8
  - RStudio version 1.1.383 or 1.1.453 (tried both)

- Symptom:
  - Dot plots in normalizer_GUI() are overlapping in Rstudio's built-in Shiny viewer, making it difficult to see and gate beads (see screenshots)

- Workaround, but it's kind of annoying:
  - Click "Open in Browser" in Rstudio's Shiny Viewer. This opens a new session of normalizer_GUI() in Google Chrome. With the zoom at 100% they are still somewhat overlapping. When I zoom out to 80%, it looks good. This gets pretty confusing though because they Shiny Viewer is still open in the background, and I need to choose the FCS file folder twice.

Thanks!

Erin

<img width="962" alt="rstudio viewer" src="https://user-images.githubusercontent.com/1001940/42391955-f3c98542-8105-11e8-869c-b9ca8232cb11.png">

<img width="1403" alt="chrome at 100" src="https://user-images.githubusercontent.com/1001940/42391954-f3b1e0a4-8105-11e8-934d-a046b1b5ec09.png">

<img width="1412" alt="chrome at 80" src="https://user-images.githubusercontent.com/1001940/42391953-f39c237c-8105-11e8-8dca-47498d20fb7a.png">

**Comment by pfgherardini** [comment]
Hi Erin,

This is fixed in the latest release, thanks for reporting. The plots are now sized to the size of the window at the time they are generated, i.e. if you make the window smaller after generating them the existing ones will overlap, but they will once again be the right size when you regenerate them (for instance by switching files)

**Comment by esimonds** [comment]
Awesome, thanks Federico!
