### ISSUE TITLE
No longer able to display Plots in Normalizer or Debarcoder

### ISSUE THREAD

**Issue by mleipold** [ParkerICI/premessa#18]
Hi,

I've been using Premessa now for several months, with no real problems.

However, this week I ran into something:  the plots no longer draw themselves in Premessa.  For example, when I call the normalizerGUI in RStudio, the window opens, I can select my FCS file directory, and then I get the dropdown menus.  The file menu lists all the relevant FCS files, but when I select one, the Ir vs bead channel plots never materialize......not even after 5-10min for a single 250K event FCS file.

If I have it open in the browser, then it *does* work, and I get the expected daughter normalized files.

I'm also able to run the Debarcoder through the web browser interface.

I can't even get old files I've previously normalized to work, now.  I've tried updating RStudio, uninstalling Shiny and Premessa and reinstalling, etc.  Nothing I do makes a difference.

One thing that's a little weird:  in the Normalizer, it's like there are placeholders for the graphs.  If I double-click in the white space under the drop-downs and buttons, I get blue rectangles, but I never get any plots.....maybe the plotting function is broken somehow?

![rstudio-premessa-problems](https://user-images.githubusercontent.com/1111114/44157588-aa0f3880-a067-11e8-98a5-abe36558c995.png)

Please advise:  as you can understand, this makes Premessa unusable.

I'm on a MacOSX, running RStudio 1.1.456, R 3.3.3.

Mike

**Comment by pfgherardini** [comment]
Hi Mike,

The browser that gets launched within RStudio as some weirdness and I don't recommend using it. You can make sure that the external browser is always opened by launching the normalizer as follows

```
normalizer_GUI(launch.browser = TRUE)
```

it is much better to use an external browser. I will probably update all my packages to make that the default

**Comment by mleipold** [comment]
Hi Federico,

OK, to confirm:  if I use that line of code, it will launch Premessa within my Firefox/etc, rather than the independent Shiny window?

Do you have any idea why it would have stopped working all of a sudden?  As far as I can tell, I hadn't changed anything (R, RStudio, Premessa versions, etc) since the last time it worked properly....


Mike

**Comment by pfgherardini** [comment]
Yes that should work (but please let me know if that's not the case). I don't know what would have changed this, but in general I recommend using a proper browser. Some of the stuff I did browser-side is non-trivial (partcularly in other packages)

**Comment by pfgherardini** [comment]
FYI i just published  a new release that has this behaviour by default

**Comment by mleipold** [comment]
Great.  I just installed 0.2.2, and can confirm that it called the Firefox window, with no Shiny standalone window.

**Comment by pfgherardini** [comment]
Thanks!
