### ISSUE TITLE
Error removing beads

### ISSUE THREAD

**Issue by givison** [ParkerICI/premessa#19]
Hi,

Got an error trying to remove beads with the normalizer GUI, I just installed the package today.

I got the following error message:

Warning: Error in remove_beads_from_file: could not find function "remove_beads_from_file"
  74: isolate
  73: observeEventHandler [/Library/Frameworks/R.framework/Versions/3.5/Resources/library/premessa/normalizer_shinyGUI/server.R#102]
   2: shiny::runApp
   1: premessa::normalizer_GUI

I think there's a typo in line 103 of normalizer_shinyGUI/server.R
 
`remove_beads_from_file(file.path(normed.dir, input$beadremovalui_selected_fcs),`
 
should be
 
`premessa::remove_beads_from_file(file.path(normed.dir, input$beadremovalui_selected_fcs),`
 
When I edited my local copy of the package it resolved the issue with the GUI.

Best,
Geoff

**Comment by pfgherardini** [comment]
You are right! Thank you very much for reporting this and identifying the fixe
