### ISSUE TITLE
Question about Normalization; also, GUI initial appearance/size

### ISSUE THREAD

**Issue by mleipold** [ParkerICI/premessa#2]
Hi,

1.  For normalization:  The Wiki states: 
"Identify beads: clicking this button will color in red the events that are recognized as beads events in the gating plots.

Apply current gates to all files: applies the current gates to all the files.

Normalize: starts the normalization routine. When the process is completed a confirmation dialog will appear

The workflow involves cycling through all the files and adjusting the beads gates in the plot, in order to identify the beads. Only events that are included in all the beads gates are identified as beads. As detailed in the dialog box that is above the row of buttons, only files for which the gates have been defined will be used as input for normalization.

You can cycle back and forth between different files, as the GUI will remember the gates you have selected for each file."

My question is about:
"applies the current gates to all the files"
"Only events that are included in all the beads gates are identified as beads."

By "all the beads gates", I assume you mean within each file, separately from the other files, right?  
For example, I had a bit of a shift in my Eu151 signal between my two files (A and B), and therefore had to nudge that.  The position of that gate in A does not affect the position of that gate in B (aside from the later normalization calculation, of course).

2.  When the GUI first opened, the x-dimension was too small:  the plots piled on top of each other, to the point that the next higher mass plot actually hid the beads (151 hid 140, 153 hid 151, etc), to where I could only see 175.  It was a simple fix to resize the Gui window, but it took me a second to realize what had happened.

**Comment by pfgherardini** [comment]
Hi Mike,

Only events that are included in all the beads gates are identified as beads -> This is the same as the matlab normalizer. The bead population is the intersection of all the beads gates in that file, that is what I intended in the documentation. 

Yes I know about the GUI size issue, I need to fix that

**Comment by pfgherardini** [comment]
Hi Mike,

FYI the plot sizing issue has ben fixed in the latest release (0.1.9) so I am closing this now
