### ISSUE TITLE
FCS files not recognized

### ISSUE THREAD

**Issue by PaulineMaby** [ParkerICI/premessa#20]
Hello,
I try to concatenente FCS files, but they are not recognized as FCS files even though they are classic FCS.3 files.
I received this message:
Error in FUN(X[[i]], ...) : 
  'file.fcs' is not a valid file

I tried
 read.FCS(in_dir,"file.fcs")
I had:
Error in if (!version %in% c("FCS2.0", "FCS3.0", "FCS3.1")) stop("This does not seem to be a valid FCS2.0, FCS3.0 or FCS3.1 file") : 
  argument is of length zero

Did that ever happen to someone else?

Please find below info about my session:
> session_info()
Session info -----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.453)           
 language (EN)                        
 collate  C                           
 tz       Europe/Paris                
 date     2018-09-22                  

Packages ---------------------------------------------------------------------------------------------------
 package      * version date       source                             
 base         * 3.5.0   2018-04-24 local                              
 Biobase        2.40.0  2018-05-01 Bioconductor                       
 BiocGenerics   0.26.0  2018-05-01 Bioconductor                       
 cluster        2.0.7-1 2018-04-13 CRAN (R 3.5.0)                     
 compiler       3.5.0   2018-04-24 local                              
 corpcor        1.6.9   2017-04-01 CRAN (R 3.5.0)                     
 datasets     * 3.5.0   2018-04-24 local                              
 DEoptimR       1.0-8   2016-11-19 CRAN (R 3.5.0)                     
 devtools     * 1.13.6  2018-06-27 CRAN (R 3.5.0)                     
 digest         0.6.17  2018-09-12 CRAN (R 3.5.0)                     
 flowCore     * 1.47.9  2018-09-22 Github (RGLab/flowCore@2827a9b)    
 graph          1.58.0  2018-05-01 Bioconductor                       
 graphics     * 3.5.0   2018-04-24 local                              
 grDevices    * 3.5.0   2018-04-24 local                              
 grid           3.5.0   2018-04-24 local                              
 lattice        0.20-35 2017-03-25 CRAN (R 3.5.0)                     
 MASS           7.3-50  2018-04-30 CRAN (R 3.5.0)                     
 matrixStats    0.54.0  2018-07-23 cran (@0.54.0)                     
 memoise        1.1.0   2017-04-21 CRAN (R 3.5.0)                     
 methods      * 3.5.0   2018-04-24 local                              
 mvtnorm        1.0-8   2018-05-31 CRAN (R 3.5.0)                     
 parallel       3.5.0   2018-04-24 local                              
 pcaPP          1.9-73  2018-01-14 CRAN (R 3.5.0)                     
 premessa     * 0.2.3   2018-09-22 Github (ParkerICI/premessa@c47abca)
 Rcpp           0.12.18 2018-07-23 cran (@0.12.18)                    
 robustbase     0.93-0  2018-04-24 CRAN (R 3.5.0)                     
 rrcov          1.4-4   2018-05-24 CRAN (R 3.5.0)                     
 stats        * 3.5.0   2018-04-24 local                              
 stats4         3.5.0   2018-04-24 local                              
 tools          3.5.0   2018-04-24 local                              
 utils        * 3.5.0   2018-04-24 local                              
 withr          2.1.2   2018-03-15 CRAN (R 3.5.0)

**Comment by pfgherardini** [comment]
Hi

It looks like this is not specific to `premessa` as even `flowCore` is having trouble with that file. If you share it with me on Box / Dropbox i can take a look

Thanks

**Comment by PaulineMaby** [comment]
Thank you very much for your interest.
I solved the problème few months ago.
I just had to update one if my R package.
It is really nice if you to propose your help anyway.
Best regards
Pauline
