### ISSUE TITLE
loss of protein marker names and corruption of files following normalization

### ISSUE THREAD

**Issue by CNicholasMDA** [ParkerICI/premessa#21]
Hello,
I am suddenly having trouble normalizing and debarcoding files properly using premessa.  Following normalization, I lose all protein marker names associated with each metal channel, and the resulting files do not look normal when placed in FlowJo. 

Can anyone suggest a troubleshooting method? I am concerned that one of the supporting packages has changed but I do not know how to diagnose it.
Thank you,
Courtney

**Comment by pfgherardini** [comment]
Hi Courtney,

Sorry for the late reply. Are you still having problems? Can you please share an example file with me?

Thanks

Federico

**Comment by CNicholasMDA** [comment]
Federico, Thanks for checking back in.  Apologies because I never closed this thread.  It looks like for now my issue has resolved.  Must've been a temporary issue.  Thanks!
-Courtney
