### ISSUE TITLE
Debarcoder updates too much, runs very slowly

### ISSUE THREAD

**Issue by givison** [ParkerICI/premessa#22]
When changing parameters for the debarcoder, the plots update when there's even a pause in typing. I think shiny's reactive values are a little bit too reactive, especially since making plots can get very computationally expensive with larger barcoded runs. It would run much more smoothly if plot updating could be tied to an update button rather than just reactive values.

**Comment by pfgherardini** [comment]
I have updated the interface in the latest release

**Comment by givison** [comment]
Thanks!
