### ISSUE TITLE
Error messeage in step "normalizer_GUI"

### ISSUE THREAD

**Issue by LilyJNJ** [ParkerICI/premessa#23]
Hi,

I have 20 .FCS files, when I use "normalizer_GUI" to normalize them one by one, 10 files can have output "xxx_normalized.fcs", but the other 10 got an error messeage: 
-------------------------------------------------------------------------------------------------------------------
Warning: Error in solve.default: system is computationally singular: reciprocal condition number = 1.00251e-19
  93: solve.default
  91: mahalanobis
  90: get_mahalanobis_distance_from_beads
  88: FUN
  87: lapply
  86: premessa::normalize_folder
  73: observeEventHandler [C:\Users\ywang535\Documents\R\R-3.4.4\library\premessa\normalizer_shinyGUI/server.R#266]
   2: shiny::runApp
   1: normalizer_GUI
-------------------------------------------------------------------------------------------------------------------
Setting is just default, as this:
![image](https://user-images.githubusercontent.com/44663456/47837018-64037e80-dde5-11e8-9597-865916078fad.png)
Screenshot of error in R is this:
![image](https://user-images.githubusercontent.com/44663456/47837042-7b426c00-dde5-11e8-9e9d-b50e02ff6ba7.png)

Can you help me with this? Thank you!

**Comment by pfgherardini** [comment]
Hi

Yes I am aware of what's causing this problem. Can you please send me one of the FCS files that causes the problem so that I can reproduce it on my computer and verify that I have a fix? You can use a Box or Dropbox link to share the file.

Thanks

Federico

**Comment by LilyJNJ** [comment]
Hi Federico,

Sorry for the late reply, just back from a business trip.
Here is the Dropbox link to a FCS file. https://www.dropbox.com/s/86hlndcav592w6q/JCLD_20180429_000909_01.FCS?dl=0
Thank you~

Best,
Lily
________________________________
发件人: Pier Federico Gherardini <notifications@github.com>
发送时间: 2018年11月9日 6:31
收件人: ParkerICI/premessa
抄送: LilyJNJ; Author
主题: Re: [ParkerICI/premessa] Error messeage in step "normalizer_GUI" (#23)


Hi

Yes I am aware of what's causing this problem. Can you please send me one of the FCS files that causes the problem so that I can reproduce it on my computer and verify that I have a fix? You can use a Box or Dropbox link to share the file.

Thanks

Federico

―

**Comment by pfgherardini** [comment]
Are you sure you are gating the beads properly? I only get that error if I leave the gates as default (which is obvioulsy incorrect), but everything works fine once the gates are adjusted

**Comment by LilyJNJ** [comment]
Hi, I'm very new to Cytof so I don't know how to gate properly... So maybe it's due to my false gating. Thank you for your help.
________________________________
发件人: Pier Federico Gherardini <notifications@github.com>
发送时间: 2018年11月29日 2:54
收件人: ParkerICI/premessa
抄送: LilyJNJ; Author
主题: Re: [ParkerICI/premessa] Error messeage in step "normalizer_GUI" (#23)


Are you sure you are gating the beads properly? I only get that error if I leave the gates as default (which is obvioulsy incorrect), but everything works fine once the gates are adjusted

―

**Comment by pfgherardini** [comment]
No problem. You have to use the plot to gate the bead population for each file, which will normally be a population in the lower right corner of the plot. See for example [here](https://github.com/ParkerICI/flow-analysis-tutorial#using-the-normalizer-gui)
