### ISSUE TITLE
Files too big

### ISSUE THREAD

**Issue by cbligaard** [ParkerICI/premessa#24]
Hi premessa team,

I am trying to preprocess my files starting with concatenation, but I keep getting this error: 
`Error in writeBin(as(t(exprs(x)), what), con, size = types[what, "bitwidth"],  : 
  only 2^31-1 bytes can be written in a single writeBin() call`

when I am running `concatenate_fcs_files`. If it helps, I have the same problem with CATALYST. I tried installing the newest version of flowCore from their github after seeing [this](https://github.com/RGLab/flowCore/issues/136) issue, but nothing changed.

Can you help me resolve this?

Best,
Christina

**Comment by pfgherardini** [comment]
Hi Christina,

Unfortunately if it's a limitation in flowCore there's not much we can do. Maybe it would be worth posting on the flowCore github issue you referenced above?

Thanks

Federico

**Comment by SamGG** [comment]
Hi Christina,
Writing big file has been improved in flowCore, as you pointed it. Could you please report the version of flowCore ? If your running flowCore version is really the latest release obtained from github, you should definitively report this error to the flowCore team.
`sessionInfo()` or `packageVersion("flowCore")`
Best

**Comment by cbligaard** [comment]
Hi Sam and Frederico, 
Thanks for the prompt replies. 

My issue seems to have been resolved - when I got the error, I had removed and installed flowCore (v. 1.94.4) and reinstalled premessa (v. 0.2.4) by using the `force=T` option. However, today I removed both packages completely, and then reinstalled both of them from scratch. This somehow made a difference. 

I apologize for the inconvenience!
