### ISSUE TITLE
Time variable is truncated

### ISSUE THREAD

**Issue by cbligaard** [ParkerICI/premessa#26]
Hi premessa team, 

I have detected a problem in the normalization process. Files are read into the program without using the truncate_max_range = F option for read.FCS, and this results in times being truncated for my concatenated files. I also think it confuses the bead normalization a lot.

Perhaps you would want to look into this?

Best, Christina

**Comment by pfgherardini** [comment]
Hi Christina,

I don't think this should create a problem but I am happy to double check. Can you please share some exmaple files with me so that I can take a look?

Thanks

Federico

**Comment by cbligaard** [comment]
Okay, thank you for looking into this!

**Comment by pfgherardini** [comment]
Can you share some example files that demonstrate the issue?
