### ISSUE TITLE
PnR value

### ISSUE THREAD

**Issue by mikejiang** [ParkerICI/premessa#29]
See https://github.com/RGLab/flowCore/issues/169
I think
https://github.com/ParkerICI/premessa/blob/8318423bc7ed44221999419b505a9693135a3648/R/fcs_io.R#L30
should be
```r
keyval[[r]] <- max(exprs.m[,i])
```
At least this is how flowCore interpret `PnR`

**Comment by pfgherardini** [comment]
Fixed, thanks for reporting!
