### ISSUE TITLE
file selection windows

### ISSUE THREAD

**Issue by bennyyclo** [ParkerICI/premessa#30]
The file selection window is not showing upon starting the normalizer_GUI().

**Comment by pfgherardini** [comment]
What OS are you using? Are you using RStudio? What version?

**Comment by bennyyclo** [comment]
Hi, I'm using ubuntu.
________________________________

**Comment by bennyyclo** [comment]
No, I'm not using Rstudio, just run it from the command line.
________________________________

**Comment by pfgherardini** [comment]
Sorry for the late reply. Are you using this on a remote server without graphical display or on a local machine? I would suggest running this from Rstudio or similar otherwise you may get a terminal prompt to input the file name manually, as opposed to a file selection dialog window
