### ISSUE TITLE
Issues with Normalizer

### ISSUE THREAD

**Issue by MLTWhite** [ParkerICI/premessa#37]
I am using premessa-0.2.6, macOS High Sierra and RStudio version 1.2.5042.

I have the same problem as #34 . I am using the sample data from 

https://github.com/nolanlab/bead-normalization/tree/master/sample_data

and I got the following error:

![Screen Shot 2020-05-14 at 11 37 54 PM](https://user-images.githubusercontent.com/61512322/82015451-012aae80-963c-11ea-8880-03a39be2fb45.png)

I typed the suggested libraries and I got the following:

![Screen Shot 2020-05-14 at 11 30 28 PM](https://user-images.githubusercontent.com/61512322/82014983-f6bbe500-963a-11ea-9a5e-db4e55bc98bd.png)

Thank you for your help!

**Comment by MLTWhite** [comment]
Solved: I needed to install Xcode. 
Thank you!

**Comment by pfgherardini** [comment]
I am not sure how installing Xcode could possibly have something to do with it. Can you tell me exactly what you did?
