### ISSUE TITLE
Harmonizer/Panel Editor-no horizontal scrolling, window collapse or hang

### ISSUE THREAD

**Issue by mleipold** [ParkerICI/premessa#5]
I had 36 files (6 files x 6 centers) that I wanted to harmonize to the same panel (some had minor issues like CD66 vs CD66b, others had more major issues).

The files were exported as new FCS from FlowJoX, and can be found here:
https://drive.google.com/drive/folders/0Bz9sd8nC272jR3VWZUtTcFRlM00?usp=sharing

I opened the Panel Editor, loaded in my files, and began to edit. I only saw 6 of the 36 files (typically Center 3).  The horizontal scroll bar in either R Studio or in the "open browser" to Firefox only appeared after I scrolled all the way to the bottom.  In Firefox, columns scrolled properly (both header/file name and column details), whereas in R Studio the header/file name never scrolled properly (maybe because the filenames are long?).

Anyway, I removed some channels, chose some others as the "correct" marker name, and then hit go.  

In R Studio:  it worked for a bit, then the GUI collapsed; I only got 12 files out of the 36 (Center 2 and Center 3) written.  Looking at the R Studio window, it appeared to get hung up:  I never got the ">" back.

Trying it in Firefox, it hung up as well, though Firefox grayed out rather than collapsing the window.

Here's what the R Studio window said when running in R Studio GUI:
-----
"Listening on http://127.0.0.1:6076
[1] "Reading FCS parameters..."
[1] "Done"
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning: Error in : all(colnames(ret$m) %in% names(names.map)) is not TRUE
Stack trace (innermost first):
    67: stopifnot
    66: rename_fcs_parameters_desc
    65: premessa:::rename_parameters_in_files
    58: isolate
    57: observerFunc [/Library/Frameworks/R.framework/Versions/3.3/Resources/library/premessa/paneleditor_shinyGUI/server.R#55]
     2: shiny::runApp
     1: paneleditor_GUI
ERROR: [on_request_read] connection reset by peer"
----

Here's what the R Studio window said when running in Firefox:
--------
Listening on http://127.0.0.1:6076
[1] "Reading FCS parameters..."
[1] "Done"
[1] "Reading FCS parameters..."
[1] "Done"
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
Warning: Error in : all(colnames(ret$m) %in% names(names.map)) is not TRUE
Stack trace (innermost first):
    67: stopifnot
    66: rename_fcs_parameters_desc
    65: premessa:::rename_parameters_in_files
    58: isolate
    57: observerFunc [/Library/Frameworks/R.framework/Versions/3.3/Resources/library/premessa/paneleditor_shinyGUI/server.R#55]
     2: shiny::runApp
     1: paneleditor_GUI

----------
The only difference I could see is that in R Studio GUI, there was the additional final line of "ERROR: [on_request_read] connection reset by peer"

As I said, I never got the ">" back indicating that it had completed....I had to hit Esc to kill the process.

I also tried running it with *no* deletions of parameters just in case that was messing things up, and the same thing happened:  only Center 2 and Center 3 had their files rewritten.

Mike

**Comment by mleipold** [comment]
FYI:  I *was* able to get the files through the cytofCore package, though the discrepancies in the columns (both number of, and marker-name) did give me a lot of "y/n" questions during execution.

In that case, I used "Center_5_P_1_MATLAB_LiveIntactSing_Linneg_CD45pos.fcs" as the template file.

**Comment by pfgherardini** [comment]
Hi Mike,

1) There is not much I can do about the issue with scrolling in RStudio. That is a limitation of the browser component that is included in RStudio
2) The error you are observing is in the R code, so it will happen irrespective of the browser you are using. Can you please take a screenshot of the renaming that you were trying to do in premessa (i.e. before you hit the process files button) so that I can reproduce it?

Thanks

**Comment by pfgherardini** [comment]
never mind I was able to reproduce it. Looking at the problem now....

**Comment by pfgherardini** [comment]
The problem is due to a bug in one of the packages I am using.

Basically any parameter name that contains the substring "NA" (such as DNA1), gets converted to an `NA` value in R, which is what is causing the problem. I am investigating a soluton to that. In the meantime if you use a different name for that parameter, that does not include the substring "NA", everything works correctly (sub-optimal I know...)

**Comment by pfgherardini** [comment]
Actually I stand corrected, the fault was in my code. @mleipold Can you please reinstall the latest version and verify it work? Thanks!

**Comment by mleipold** [comment]
@pfgherardini 
I reinstalled Premessa this morning.  

Successes:
1.  I was able to get it to finish and output FCS files.
2.  Channels I asked it to excise were excised.

Failures:
1.  Channels were not renamed properly.
A.  The Ir191 and Ir193 channels were not corrected to "DNA1" and "DNA2" as requested.  Whether this is related to the "NA" issue you mention above, I'm not sure.  It appears to have just left them alone:  for example, Center 2's files are still "cells1" and "cells2".
B.  Center 3 still has the weird marker naming.  For example, "Ce140Di::Bead1-Ce140", rather than "Ce140Di::Bead1" like all the other files.


Mike

**Comment by pfgherardini** [comment]
In order to rename the parameters you have to edit the cells under the corresponding file column (see attached screenshot, i.e. things don't get renamed automatically)
Please note that, in order to make editing easier, you can select multiple cells (with shift+click or ctrl+click, similar to what you would do in Excel).

I have tested it with your files and things are renamed correctly. If things are still not working for you can you please send me a screenshot of the final state of the table before you hit the "process files" button? You can do it with just 2-3 files to keep things easier.

<img width="792" alt="capture" src="https://user-images.githubusercontent.com/2983220/30819906-2bcfacf2-a1d5-11e7-952d-c28c04502f20.PNG">

**Comment by mleipold** [comment]
I'm not sure I understand:  my assumption had been that "Most common" (or, whatever I modify in that column) was what got applied to all files when I hit the "Rename" button.  This seemed reasonable, since I do not see in the documentation that I need to select an entire row to apply the "Most common" change.

I would *not* want to check the "Remove" box (gray, above), if I'm just modifying a name.  How else can I select an entire row?

Or, are you saying I have to go in column by column and make changes to each file?

**Comment by pfgherardini** [comment]
No the "Most common" is just for visualization purpose (I see that I probably need to make the documentation clearer), i.e. it *displays*  the most common value across the row.

Manual editing should not be too bad. If you have to rename a channel in a bunch of files, you can select the cell that correspond to the first file, then scroll to the last file and shift+click on the last cell you want to edit. This will select all the intervening cells, so that now when you copy with ctrl+V, it will copy in all the cells you have selected. Is my explanation clear? Works the same way as Excel basically

**Comment by mleipold** [comment]
Is there a way to add a column for what things *should* be changed to, across all columns?  So, Remove, Parameter, Most Common, then something like "Change to" or "Output as".  Kind of like the template file you can put in cytofCore?

My original thought was that this aspect of Premessa would allow harmonization without having to individually modify things.  In these 36 files (6 files x 6 centers), I have one center where all 23 or so parameters have the extended naming mentioned earlier.  That's a lot of typing, even with the select feature you mentioned.

I can understand the reason for the granularity you describe, but I'm not sure that people will actually commonly use it that way.  I see more people being interested in the cytofCore-like "rename according to my template" feature, though I think your "Most Common" column is a great added idea that helps the user see what most files have.

Maybe you could make the "Output as" column clickable; that way you could do the granularity, *or* have the option of applying that column to everything,


I will also say:  There *is* at least one case where everything *does* get applied new.  Center 1 had Lu176 rather than Yb176 like all the other centers.  If I took just the Center 1 files and modified Parameter from Lu176 to Yb176 then executed, it *did* rename all the Lu176 to Yb176.  And that was without selecting all 6 files across that row.

Maybe it worked because there were no additional name conflicts in that channel for those 6 files, I don't know.  But it did work.

**Comment by pfgherardini** [comment]
I can add an option to copy the value of the "most common" cells and copy it across the rows, that would be a pretty easy modification.

The thing you mentioned worked because you are talking about the parameter name ($PxN) value, not the description ($PxS) value. The cells under the file-specific columns are for the $PxS, that first parameter column is for the $PxN, which needs to be the same across all files, for the operation to even make sense.

From the docs

" This information is then displayed in a table, where each row corresponds to a different parameter name ($PnN keyword), indicated by the row names (leftmost column), and each column corresponds to a different file, indicated in the column header. Each cell represents the description string ($PnS keyword) of a specific parameter in a given file. "

**Comment by mleipold** [comment]
Ah, ok the N vs S thing explains most of it.  But is $PxN *intended* to be editable in that way?  I mean, I'm glad that it is, but I'm a little curious why I didn't get an error message of some sort or a failure to execute.

Maybe have the "Output as" column initial value or default be equal to "Most Common", but "Output as" would be editable and would be the final word in how the files come out?

**Comment by pfgherardini** [comment]
why would you get an error message in that case? The software correclty changed the $PxN  for that parameter as specified. 

I'll add a button to expedite things in cases where you simply want to use the "Most common" value, but I have weird convoluted cases in the past where the granularity was actually required.

**Comment by mleipold** [comment]
As a side note:  Since Center 1 was the only file set which had Lu176-CD56, I tried altering that in the Parameter when all 36 files were present.

What I didn't fully appreciate (because of the number of files) was that another center had acquired both Yb176-CD56 and Lu176-bead5, and therefore changing "Lu176-" to "Yb176-CD56" would give it a conflict.

The Panel Editor allowed me to make the change, but when I hit execute, the GUI collapsed and RStudio gave me this error message:
"Listening on http://127.0.0.1:6968
[1] "Reading FCS parameters..."
[1] "Done"
[1] "Processing /Users/michaelleipold/Customer stuff/Gates Foundation/Multicenter-results/LiveIntactSinglets-Linneg-CD45pos/subset of original files/Center_3_A_1_MATLAB_LiveIntactSing_Linneg_CD45pos.fcs ..."
Warning in flowCore::write.FCS(flowFrame, path) :
  'write.FCS' is not fully tested and should be considered as experimental.
[1] "Processing /Users/michaelleipold/Customer stuff/Gates Foundation/Multicenter-results/LiveIntactSinglets-Linneg-CD45pos/subset of original files/Center_2_A_1_MATLAB_LiveIntactSing_Linneg_CD45pos.fcs ..."
Warning: Error in : !any(duplicated(new.names)) is not TRUE
Stack trace (innermost first):
    67: stopifnot
    66: rename_fcs_parameters_name
    65: premessa:::rename_parameters_in_files
    58: isolate
    57: observerFunc [/Library/Frameworks/R.framework/Versions/3.3/Resources/library/premessa/paneleditor_shinyGUI/server.R#55]
     2: shiny::runApp
     1: paneleditor_GUI
ERROR: [on_request_read] connection reset by peer"

Again, I didn't get my ">" without hitting escape.

Obviously, that was a mistake on my part.  But is there a way to make it default to Escaping to the ">" prompt in the case of any general error like that?

**Comment by pfgherardini** [comment]
No i don't think there is a way to do that, but I'll look into it. Yes that's definitely a mistake, you cannot have two parameters with the same $PxN in the same file
