### ISSUE TITLE
Normalizing 1 file-no before/after plots

### ISSUE THREAD

**Issue by mleipold** [ParkerICI/premessa#7]
[beads_before_and_after.pdf](https://github.com/ParkerICI/premessa/files/1532365/beads_before_and_after.pdf)

Hi,

When normalizing just *ONE* file (large-ish barcoded sample that would then be debarcoded into multiple smaller samples), the "beads before and after" picture gets generated, but isn't really *populated*.

Please see attached PDF.

I think it's an issue of R is drawing line segments from Point 1 (file 1) to Point 2 (file 2); if there's no Point 2, then there can't be a line segment.

Possible solutions:
1.  Default to drawing dots at the appropriate signal intensities for each channel.
2.  Switch depiction to show Before and After on the same plot (Point/file 1 = Before, Point/File 2 = After).
3.  Something else?

Mike

**Comment by mleipold** [comment]
If I take the same file and put it through the MATLAB version, I *do* get a plot.  See attached PNG 
![120117_beads_before_and_after](https://user-images.githubusercontent.com/1111114/33626644-0a37c3b4-d9b0-11e7-9332-498a0e5c0070.png)


As far as I can tell, the special case of N=1 makes the x-axis become "Time" rather than "File name" (which is the default for N>1)


Mike

**Comment by pfgherardini** [comment]
I have added this in the latest release. Specifically now, for each sample, a plot of beads vs time is generated in the beads_vs_time subfolder (see documentation for more details)
