### ISSUE TITLE
Error when trying to use paneleditor

### ISSUE THREAD

**Issue by knmorrow** [ParkerICI/premessa#8]
Hi,

I am able to initiate the panel editor just fine and select the FCS file I want to alter, but when I click the button in the UI to process files I always get the following error:

Listening on http://127.0.0.1:3114
[1] "Reading FCS parameters..."
[1] "Done"
Warning: Error in do.call: second argument must be a list
Stack trace (innermost first):
    66: do.call
    65: rhandsontable::hot_to_r
    58: isolate
    57: observerFunc [/Users/knmorro/Library/R/3.4/library/premessa/paneleditor_shinyGUI/server.R#54]
     2: shiny::runApp
     1: paneleditor_GUI
ERROR: [on_request_read] connection reset by peer

**Comment by pfgherardini** [comment]
Hi,

Can you send me a screenshot of what the interface looks like, just before you press the process button? You can't really select a single file to process (i.e. all the files in the table get processed). Seeing a screenshot will help me understand what you are doing.

Thanks

**Comment by knmorrow** [comment]
![selecting a file](https://user-images.githubusercontent.com/36202683/35922106-a9dc0170-0bea-11e8-8bba-f1287c9adf0b.jpg)
![after selecting file before clicking process](https://user-images.githubusercontent.com/36202683/35922110-ac97bd96-0bea-11e8-98ff-8753df5cf8fb.jpg)

**Comment by pfgherardini** [comment]
Hi

There seem to be an issue with the latest version of one of the packages I am using to display the table. Let me investigate and I'll get back to you ASAP

Federico

**Comment by pfgherardini** [comment]
Should be fixed in the latest release. Please install premessa again and let me know if you still have problems

**Comment by knmorrow** [comment]
It is working now! Thank you

**Comment by jgarces02** [comment]
Hi @pfgherardini, 

I've another error using `paneleditor_GUI()`. I paste the code/error I used below and a screenshot of the GUI.
```
> paneleditor_GUI()
Listening on http://127.0.0.1:4080
Reading FCS parameters...
Done
Warning in dir.create(out.dir, recursive = T) :
  'G:\Mi unidad\Proyectos\FlowCT_Ciro\files_FlowCT\renamed' already exists
[1] "Processing G:/Mi unidad/Proyectos/FlowCT_Ciro/files_FlowCT/MO_017294.fcs ..."
Warning: Error in rename_fcs_parameters_name: is.matrix(m) is not TRUE
  62: <Anonymous>
```
![image](https://user-images.githubusercontent.com/27858969/54678099-b7f8d080-4b04-11e9-995f-b325a6730739.png)
 Thanks in advance for your help!
